###
POST http://localhost:50000/api/v2/clients/bill HTTP/1.1
Content-Type: application/json

{
  "client_name": "test2",
  "dni": "1238"
}

###
GET http://localhost:50000/api/v2/clients/ HTTP/1.1

###
GET http://localhost:50000/api/v2/clients/62426f779eeb2b2892723e21 HTTP/1.1

###
PUT http://localhost:50000/api/v2/clients/62426f779eeb2b2892723e21 HTTP/1.1
Content-Type: application/json

{
  "client_name": "juan naranjo",
  "dni": "1234"
}

###
DELETE http://localhost:50000/api/v2/clients/62426f779eeb2b2892723e21  HTTP/1.1